#
# Database
#

database:

  # Examples:
  #
  # "mongodb://user:password@host:port/database"
  # "user:password@host:port/database"
  # "host/database"
  #
  # For replica set join all addresses into one string, separated by comma.
  #
  mongo: localhost/fontello-dev

